### PR TITLE
Caseys feat

### PR DESCRIPTION
**Pull request by Kredcool**
I don't really know what I am doing so we want both of the birthday messages.

### CODE REVIEW

**Review by KenwoodFox — APPROVED** [review]
I think this is really silly and annoying perhaps but, i approve.

Where is the "robot channel" are you spamming somewhere important?

:+1:

**Comment by Kredcool** [comment]
the robot channel is the robot channel on the discord it houses the bot that doesn't work

**Comment by KenwoodFox** [comment]
Okaayy.. i guess lol?

ur good to merge if ur ok with that channel then, don't forget to `squash and merge` please

**Comment by TheYellowGamer** [comment]
Make sure that on the subjects birthday it does not congratulate them

**Comment by KenwoodFox** [comment]
> Make sure that on the subjects birthday it does not congratulate them

What are their birthdays?

@Kredcool if this is a thing we're gonna be doing can we store all this data as a yaml and just iter through it? i don't want a million tasks running for random ppl's birthdays

**Comment by Kredcool** [comment]
I'm debating to if I should remove it, myself because this doesn't serve much of a purpose and the channel is muted for most people so they most likely don't see it

**Comment by KenwoodFox** [comment]
Idk if this is a feature we really need either, are any other students using this @TheYellowGamer?

**Comment by Kredcool** [comment]
I know Logan has set it up to do this to Veronica, and Casey has done it with Mat but I am not sure if they are seeing it or if they would notice it being gone

**Pull request merged**
